# -*- coding: utf-8 -*-
"""R_Python_Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PythonVersusR/basicDataStructures_lists/blob/main/R_Python_Lists.ipynb

<a target="_blank" href="https://colab.research.google.com/github/PythonVersusR/basicDataStructures_lists/blob/main/R_Python_Lists.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


# Lists in R and Python
"""

## JUAN DIEGO GUTIERREZ CORTEZ - 20172174

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

"""## 1. Creating"""

numeros_primosP = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
lista_patronesP = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
capitalesP = ['Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma']
matrizP = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

type(numeros_primosP)

numeros_primosP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# numeros_primosR=list(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# 
# lista_patronesR=list(c(1), c(1, 2), c(1, 2, 3), c(1, 2, 3, 4), c(1, 2, 3, 4, 5))
# 
# capitalesR=list('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# 
# matrizR=list(c(1, 2, 3), c(4, 5, 6), c(7, 8, 9))
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# typeof(numeros_primosR)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# numeros_primosR

"""## 2. Accessing"""

# Keep in mind the positions in Python start in **0**.
lista_patronesP[0]

type(lista_patronesP[0])

# Commented out IPython magic to ensure Python compatibility.
# %%R
# lista_patronesR[[1]]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# typeof(lista_patronesR[[1]])

# Commented out IPython magic to ensure Python compatibility.
# %%R
# lista_patronesR[[1]]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# typeof(lista_patronesR[[1]])

#last element
capitalesP[-1]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# tail(capitalesR,1)

"""### Slices"""

# consecutive
agesP[1:4] #second to fourth

# Commented out IPython magic to ensure Python compatibility.
# %%R
# agesR[2:4]

# non consecutive with step or pattern
agesP[1:8:2] # second to eight step 2

# Commented out IPython magic to ensure Python compatibility.
# %%R
# agesR[seq(2,8,2)]

# non consecutive without step or pattern
keepIndex=[0, 2, 3]
[agesP[i] for i in keepIndex]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# agesR[c(1,3,4)]

"""## Replacing

### by Position
"""

matrizP[2]="Spain"

# list changed:
matrizP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# matrizR[[3]]="Spain"
# 
# # list changed:
# matrizR

"""### By Value"""

lista_patronesP[lista_patronesP=="China"]="PR China"
lista_patronesP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# lista_patronesR[lista_patronesR=='China']="PR China"
# lista_patronesR

"""## Deleting

### By Position
"""

numeros_primosP = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

numeros_primosP.pop(-1)

print(numeros_primosP)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# numeros_primosR[length(numeros_primosR)]=NULL
# numeros_primosR

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# numeros_primosR =list(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# 
# numeros_primosR[2:4]=NULL
# 
# #now:
# numeros_primosR

# 'del' works for several positions

numeros_primosP = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

del numeros_primosP[1:4]

#now:
numeros_primosP

# non consecutive
numeros_primosP = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
byeIndex=[2, 4, 7]
numeros_primosP=[numeros_primosP[i] for i in range(len(numeros_primosP)) if not i in byeIndex]
numeros_primosP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# numeros_primosR=list(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# numeros_primosR[c(1,8,10)]=NULL
# numeros_primosR

"""### by Value"""

# by value
capitalesP = ['Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma']
capitalesP.remove('Buenos Aires')

# list changed:
capitalesP # just first ocurrence of value!!

# deleting every  value:

capitalesP = ['Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma']
capitalesP=[p for p in capitalesP if not p in ['a']]

# you get:
capitalesP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# capitalesR=list('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# capitalesR=capitalesR[!capitalesR %in% list('Bogotá')]
# capitalesR
#

"""## Inserting values"""

# at the end
capitalesT = ['Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma']
capitalesT.append("Salamanca")
capitalesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# capitalesT=list('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# capitalesT=append(capitalesT,'Salamanca')
# capitalesT

# specific position
capitalesT=['Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma']
capitalesT.insert(2,"Salamanca")
capitalesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# capitalesT=list('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# capitalesT=append(capitalesT,'Salamanca',after=2)
# capitalesT

"""## Concatenating"""

numeros_primosT = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
lista_patronesT = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
numeros_primosT + lista_patronesT

numeros_primosT = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
lista_patronesT = [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
lista_patronesT.extend(numeros_primosT)
lista_patronesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# numeros_primosT=list(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# 
# capitalesT=list('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# 
# resultado=c(numeros_primosT, capitalesT)
# 
# print(resultado)
#

#notice
numeros_primosT=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
lista_patronesT=[[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]
numeros_primosT.append(lista_patronesT)
numeros_primosT