# -*- coding: utf-8 -*-
"""JuanDiego_Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2se4z9APZYpfk34tvTiB6uhsbN4He4u

<a target="_blank" href="https://colab.research.google.com/github/PythonVersusR/basicDataStructures_tuples/blob/main/Python_Tuples.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

#  **TUPLES**

Tuples are inmutable structures in Python, they look like lists but do not share much of their functionality:
"""

ABECEDARIOS="a", "b", "c"

type(ABECEDARIOS)

"""You can access:"""

ABECEDARIOS[1]

"""But no other operation is allowed:"""

del ABECEDARIOS[2]

ABECEDARIOS[2]='d'

ABECEDARIOS[3]='e'

"""You can concatenate two tuples into a new one:"""

Reest='f','g', 'h', 'i','j','k', 'l', 'm',
Reest

allABECEDARIO=ABECEDARIOS + Reest
allABECEDARIO

"""But it has not altered any previous tuple."""