# -*- coding: utf-8 -*-
"""JuanDiego_Vectores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YeWP7yU2v4927yi6wuFOdr5tjjl7q3N
"""

#JUAN DIEGO GUTIERREZ CORTEZ

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

"""## 1. Creating"""

import numpy as np

Numeros_Primos_P = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])
capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))
PatronesP = np.array([[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]], dtype=object)
RandomP = np.array([10, 'Hola', 3.14, True])

Numeros_Primos_P

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# Numeros_Primos_P <- c(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# PatronesP <- list(c(1), c(1, 2), c(1, 2, 3), c(1, 2, 3, 4), c(1, 2, 3, 4, 5))
# RandomP <- c(10, 'Hola', 3.14, TRUE)
#

# Commented out IPython magic to ensure Python compatibility.
# %%R
# RandomP

"""## 2. Accessing"""

# Keep in mind the positions in Python start in **0**.
Numeros_Primos_P[0]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# CapitalesP[1]

#last element
Numeros_Primos_P[-1]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# tail(CapitalesP,1)

"""### Slices"""

# several, using slices:
Numeros_Primos_P[3:4] #second to fourth

# Commented out IPython magic to ensure Python compatibility.
# %%R
# CapitalesP[2:4]

# non consecutive

Numeros_Primos_P[[1,4,10]]

# Commented out IPython magic to ensure Python compatibility.
# %%R
# CapitalesP[c(1,3,4)]

"""## Replacing

### by Position
"""

RandomP[3]="Salamanca"

# list changed:
RandomP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# RandomP[3]="Salamanca"
# 
# # list changed:
# RandomP

"""### By Value"""

RandomP=np.char.replace(RandomP, '10', '65465')
RandomP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# RandomP[RandomP=='10']="PR China"
# RandomP

"""## Deleting

### By Position
"""

PatronesP=np.delete(PatronesP,-1)
PatronesP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# CapitalesP=CapitalesP[-length(CapitalesP)]
# CapitalesP

# for several positions

capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))
capitalesT=np.delete(capitalesT,range(2,4))
#now:
capitalesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# CapitalesP=CapitalesP[-c(2:4)]
# 
# #now:
# CapitalesP

import numpy as np

byeIndex = [2, 6, 5]

capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))

new_vectorP = np.delete(capitalesT, byeIndex)

new_vectorP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# CapitalesP=CapitalesP[-c(1,3,5)]
# CapitalesP

"""### by Value"""

# by value
capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))

capitalesT=np.delete(capitalesT, np.where(capitalesT == 4))

#  changed:
capitalesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# CapitalesP=CapitalesP[CapitalesP!=5]
# CapitalesP
#

# by value
capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))

#vectorP=
capitalesT=np.delete(capitalesT, np.isin(capitalesT,[1,35]))

#  changed:
capitalesT

# Commented out IPython magic to ensure Python compatibility.
# %%R
# 
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# CapitalesP=CapitalesP[!CapitalesP%in%c(5,35)]
# CapitalesP

"""## Inserting values

### at the End
"""

RandomP = np.array([10, 'Hola', 3.14, True])
RandomP=np.append(RandomP,5)
RandomP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# RandomP <- c(10, 'Hola', 3.14, TRUE)
# RandomP=c(RandomP,489)
# RandomP

"""### in a particular location"""

RandomP = np.array([10, 'Hola', 3.14, True])
RandomP=np.insert(RandomP,obj=1,values=80) #obj is position
RandomP

# Commented out IPython magic to ensure Python compatibility.
# %%R
# RandomP <- c(10, 'Hola', 3.14, TRUE)
# RandomP=append(RandomP,45949,after=1)
# RandomP

"""## Concatenating"""

import numpy as np


Numeros_Primos_P = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])
capitalesT = np.array(('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma'))
Paises_Capitales=np.concatenate((Numeros_Primos_P,capitalesT))
Paises_Capitales

# Commented out IPython magic to ensure Python compatibility.
# %%R
# Numeros_Primos_P <- c(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47)
# CapitalesP <- c('Lima', 'Bogotá', 'Buenos Aires', 'Brasilia', 'Ciudad de México', 'Madrid', 'Lisboa', 'Atenas', 'París', 'Roma')
# Paises_capitalesR=c(CapitalesP,Numeros_Primos_P)
# Paises_capitalesR

"""Remember that vectors support just one data type, and coercion will activate when different data types are detected."""

Numeros_Primos_P = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,'o'])
Numeros_Primos_P

# Commented out IPython magic to ensure Python compatibility.
# %%R
# vectorR1=c(1,2,3,4,"o")
# vectorR1